version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: jpahibernate
      MYSQL_USER: myuser
      MYSQL_PASSWORD: pass123